### ISSUE TITLE
what about using React for frontend?

### ISSUE THREAD

**Issue by sibelius** [opensource9ja/dnotebook#1]

**Comment by risenW** [comment]
This is definitely out next line of action. But neither of us are good frontend react engineers. If you can lead this, we can definitely discuss further to make it better.

**Comment by katheecv** [comment]
Hi! I have experience working with React JS and I would like to help you.

**Comment by risenW** [comment]
Great! I can walk you through the internals and what we are planning, and more importantly, hear your ideas for making this better. Should we hop on a call to discuss this further, sometime next week if that works for you.

**Comment by katheecv** [comment]
That sounds great. See you next week.

**Comment by risenW** [comment]
> That sounds great. See you next week.

I'm sorry for the delay. Can you send me an email so we can schedule a meeting?

 Mail to: risingodegua@gmail.com

**Comment by GantMan** [comment]
How's the React version coming along?

**Comment by steveoni** [comment]
@GantMan  @katherinecv the react version is located here https://github.com/opensource9ja/dnotebook-react . It is a work in progress, the internals of Dnotebook is fully implemented, but the user interface is still a work in progress
