### ISSUE TITLE
Creating, using and managing multiple notebooks

### ISSUE THREAD

**Issue by risenW** [opensource9ja/dnotebook#13]
Users can open more than one Notebook in a tab. Ideally, we should execute each notebook in a separate context. This is similar to Kernels in Jupyter notebooks. 

This ensures that multiple notebooks can be run simultaneously, and each manages its own state.

## Acceptance
* [x] User can run multiple notebooks simultaneously
* [x] User can start and manage notebook context

**Comment by AceTheCreator** [comment]
@risenW wanna assign this issue to me?

**Comment by risenW** [comment]
> @risenW wanna assign this issue to me?

I fixed this already, and didn't use child process. I ended up using a context object. I'll update the issue description
