### ISSUE TITLE
How to save data into csv file in dnotebook?

### ISSUE THREAD

**Issue by cdjim** [opensource9ja/dnotebook#8]
Hi there, thanks for creating this project and making data analysis easier in the JavaScript world.

I am cleaning up some data and would like to save the result into local file, e.g. csv format. Does dnotebook supports this and how? 

Using Danfo.js, DataFrame.to_csv could save the result to local drive. But in dnotebook, there is no any files saved after execute to_csv. Below is the my code.

`var data = {
  "Abs": [20.2, 30, 47.3] ,
  "Count": [34, 4, 5] ,
  "country code": ["NG", "FR", "GH"] 
}
let df = new dfd.DataFrame(data)
df.to_csv("./try_data.csv").then((csv) => {
    console.log(csv);

}).catch((err) => {

    console.log(err);
})`

**Comment by Sanchayata** [comment]
I also have the same question. Please look into this @GantMan @steveoni @risenW @AceTheCreator

**Comment by risenW** [comment]
> I also have the same question. Please look into this @GantMan @steveoni @risenW @AceTheCreator

Hi, you can now download files even in the browser. So update to the latest Danfojs, and use the toCSV function. See : 

`
df.toCSV({ fileName: "testOut.csv", download: true});

`

**Comment by Sanchayata** [comment]
I tried that but in dnotebook it is not giving me any output or downloading anything. Can you suggest what might be the issue? @risenW

**Comment by Sanchayata** [comment]
> > I also have the same question. Please look into this @GantMan @steveoni @risenW @AceTheCreator
> 
> Hi, you can now download files even in the browser. So update to the latest Danfojs, and use the toCSV function. See :
> 
> ` df.toCSV({ fileName: "testOut.csv", download: true});
> 
> `

This is the code i used:
Xtrain.to_csv({ filePath: "Newtrain.csv",  download: true})

But it shows no result and nothing gets downloaded.

Can you please help regarding this @risenW @GantMan @steveoni ?

**Comment by Sanchayata** [comment]
> > I also have the same question. Please look into this @GantMan @steveoni @risenW @AceTheCreator
> 
> Hi, you can now download files even in the browser. So update to the latest Danfojs, and use the toCSV function. See :
> 
> ` df.toCSV({ fileName: "testOut.csv", download: true});
> 
> `

This is not possible in dnotebook. Can you suggest how we can do it in dnotebook? 
@GantMan @steveoni @risenW @AceTheCreator @geoffrey1330

**Comment by AceTheCreator** [comment]
@Sanchayata I'll look into this issue and get back. Thanks for raising this issue
